# Plugin version. DO NOT CHANGE THIS MANUALLY!
Version: '${project.version}'

##########################################################

# Dictates when we execute the removal of blocks.
# Possible values:
# BEFORE_STRUCTURES: Structures generated after removal -> Structures stay intact.
# AFTER_STRUCTURES: Structures generated before removal -> Structures do not stay intact.
ExecuteMode: BEFORE_STRUCTURES

##########################################################

# Amount of empty space between each block.
# Valid range [1, 7].
BlockSpacing: 3

##########################################################

# Whether to skip all bedrock generation.
RemoveAllBedrock: true

##########################################################

# Whether to temporarily disable water flow and block gravity in newly generated chunks.
# Reduces lag by not allowing liquids to start flowing instantly when the chunk is loaded.
DisableEventsInNewChunks: true

##########################################################

# Blocks that never get removed by the generator.
# For example if using 'LoadMode: AFTER_STRUCTURES' which removes blocks from structures too,
# you could add 'END_PORTAL_FRAME' here to save parts of it from being deleted.
NonReplaceableBlocks:
# - SPAWNER
# - CHEST

##########################################################