# When to generate the grid.
# BEFORE_DECORATIONS: Faster, but leaves all decorations (structures, trees, etc) intact.
# AFTER_DECORATIONS: Slower, but decimates everything except blocks defined in "NonReplaceableBlocks" (below).
GenerationMode: AFTER_DECORATIONS

# Amount of empty space between each block.
# Valid range [1, 7].
BlockSpacing: 3

# Whether to skip all bedrock generation.
RemoveAllBedrock: true

# Whether to disable decay for naturally generated leaf blocks.
DisableNaturalLeafDecay: true

# Whether to disable popping off naturally generated item frames.
DisableNaturalItemFramePop: true

# Whether to TEMPORARILY disable water flow and block gravity in newly generated chunks.
# Reduces lag by not allowing liquids to flow when the chunk is loaded.
DisableEventsInNewChunks: true

# Blocks that never get removed by the generator.
NonReplaceableBlocks:
  - END_PORTAL_FRAME
# - SPAWNER
# - CHEST